"""Main Click CLI entrypoint for vops."""

import logging
import shutil
import sys
from pathlib import Path
import click

from videoops.cli.banner import print_banner
from videoops.config import settings

logger = logging.getLogger("videoops.cli")


@click.group(invoke_without_command=True)
@click.pass_context
def cli(ctx: click.Context) -> None:
    """vops — Code-to-Canvas AI Video Production CLI."""
    if ctx.invoked_subcommand is None:
        print_banner()
        click.echo(ctx.get_help())


@cli.command("help")
@click.argument("command_name", required=False)
@click.pass_context
def help_cmd(ctx: click.Context, command_name: str | None) -> None:
    """Display help information for vops or a specific subcommand."""
    print_banner()
    if command_name:
        cmd = cli.get_command(ctx, command_name)
        if cmd:
            cmd_ctx = click.Context(cmd, info_name=command_name, parent=ctx)
            click.echo(cmd.get_help(cmd_ctx))
        else:
            click.secho(f"Unknown command '{command_name}'.\n", fg="red", bold=True)
            click.echo(cli.get_help(ctx))
    else:
        click.echo(cli.get_help(ctx))


@cli.command("init")
def init_cmd() -> None:
    """Initialize a new VideoOps project configuration (config.yaml)."""
    print_banner()
    target_config = Path.cwd() / "config.yaml"
    template_path = Path(__file__).parent / "templates" / "config.yaml.tpl"

    if target_config.exists():
        click.secho(f"⚠️  config.yaml already exists at {target_config}", fg="yellow", bold=True)
        return

    if not template_path.exists():
        click.secho(f"❌ Template file not found at {template_path}", fg="red", bold=True)
        sys.exit(1)

    try:
        shutil.copyfile(template_path, target_config)
        click.secho(f"✨ Successfully initialized project config: {target_config}", fg="green", bold=True)
        click.echo("   Edit config.yaml to customize topic, duration, captions, audio, and publishing options.\n")
    except Exception as e:
        click.secho(f"❌ Failed to create config.yaml: {e}", fg="red", bold=True)
        sys.exit(1)


@cli.command("produce")
@click.option("--topic", "-t", default=None, help="Video topic or headline override.")
@click.option("--mode", "-m", type=click.Choice(["auto", "video", "image"]), default="auto", help="Visual asset acquisition mode.")
@click.option("--publish/--no-publish", default=None, help="Override auto YouTube publishing setting.")
def produce_cmd(topic: str | None, mode: str, publish: bool | None) -> None:
    """Execute end-to-end Shorts production pipeline."""
    print_banner()

    # Load topic from config if not passed
    if not topic:
        cfg = settings.script_config
        topic = cfg.get("default_topic")

    click.secho(f"🚀 Launching VideoOps production pipeline for topic: '{topic}' (mode: {mode})", fg="cyan", bold=True)

    if publish is not None:
        settings.ENABLE_YOUTUBE_UPLOAD = publish

    from videoops.pipeline.orchestrator import ShortsPipelineOrchestrator
    orchestrator = ShortsPipelineOrchestrator()

    try:
        video_path, thumbnail_path = orchestrator.run(topic=topic, mode=mode)
        click.echo("\n" + "═" * 60)
        click.secho("🎉 VIDEO PRODUCTION COMPLETED SUCCESSFULLY!", fg="green", bold=True)
        click.echo(f"  🎬 Rendered Video : {video_path}")
        click.echo(f"  🖼️  Thumbnail      : {thumbnail_path}")
        click.echo("═" * 60 + "\n")
    except Exception as e:
        click.secho(f"❌ Pipeline execution failed: {e}", fg="red", bold=True)
        sys.exit(1)


@cli.command("publish")
@click.option("--video", "-v", required=True, type=click.Path(exists=True), help="Path to rendered MP4 video file.")
@click.option("--title", default="YouTube Short", help="Video title.")
@click.option("--description", default="Generated by VideoOps 1.0 #Shorts", help="Video description.")
@click.option("--thumbnail", type=click.Path(exists=True), default=None, help="Path to thumbnail image file.")
def publish_cmd(video: str, title: str, description: str, thumbnail: str | None) -> None:
    """Publish a rendered video to YouTube via OAuth."""
    print_banner()
    click.secho(f"📤 Publishing '{video}' to YouTube...", fg="cyan", bold=True)

    from videoops.publishing.youtube import YouTubePublisher
    publisher = YouTubePublisher()

    try:
        publisher.publish(
            video_path=video,
            title=title,
            description=description,
            thumbnail_path=thumbnail,
        )
        click.secho("✅ Video successfully published!", fg="green", bold=True)
    except Exception as e:
        click.secho(f"❌ Publishing failed: {e}", fg="red", bold=True)
        sys.exit(1)


@cli.command("info")
def info_cmd() -> None:
    """Display VideoOps system configuration, FFmpeg, and environment details."""
    print_banner()

    import psutil
    import platform

    config_file = Path.cwd() / "config.yaml"
    has_config = config_file.exists()

    click.secho("System Environment & Configuration:", fg="yellow", bold=True)
    click.echo(f"  • Version        : 0.2.3")
    click.echo(f"  • OS / Python    : {platform.system()} {platform.release()} (Python {sys.version.split()[0]})")
    click.echo(f"  • Config File    : {'✅ ' + str(config_file) if has_config else '⚠️  Not found (run `vops init` to create)'}")
    click.echo(f"  • LLM Base URL   : {settings.LLM_BASE_URL}")
    click.echo(f"  • LLM Model      : {settings.LLM_MODEL}")
    click.echo(f"  • Captions       : {'Enabled' if settings.captions_enabled else 'Disabled'}")
    click.echo(f"  • Output Dir     : {settings.resolved_output_dir}")
    click.echo(f"  • Temp Sandbox   : {settings.resolved_temp_dir}")

    # Check FFmpeg on PATH
    ffmpeg_path = shutil.which("ffmpeg")
    click.echo(f"  • FFmpeg Binary  : {'✅ ' + ffmpeg_path if ffmpeg_path else '❌ Not found on PATH'}")

    # RAM and CPU check
    mem = psutil.virtual_memory()
    click.echo(f"  • System RAM     : {mem.available / (1024**3):.2f} GB available / {mem.total / (1024**3):.2f} GB total")
    click.echo(f"  • CPU Cores      : {psutil.cpu_count(logical=True)} logical cores")
    click.echo()


def main() -> None:
    """CLI execution entrypoint."""
    cli()


if __name__ == "__main__":
    main()
