"""Pure domain entities and immutable value objects for videoops.

Strictly ZERO external dependencies. Standard library only.
"""

from dataclasses import dataclass
from enum import Enum


class VoiceStyle(str, Enum):
    """Voice style presets for TTS synthesis."""
    EXCITED = "excited"
    CALM = "calm"
    SERIOUS = "serious"
    CASUAL = "casual"
    NONE = "none"


class AssetType(str, Enum):
    """Media asset types."""
    AUDIO = "audio"
    IMAGE = "image"
    VIDEO = "video"


@dataclass(frozen=True, slots=True)
class ScriptCard:
    """A single storyboard section card in a video script."""
    text: str
    duration: float
    voice_style: VoiceStyle = VoiceStyle.EXCITED
    background_query: str | None = None


@dataclass(frozen=True, slots=True)
class ContentPackage:
    """Complete script and metadata package generated by LLM story engine."""
    title: str
    description: str
    script_cards: tuple[ScriptCard, ...]
    thumbnail_hf_prompt: str | None = None
    thumbnail_unsplash_query: str | None = None


@dataclass(frozen=True, slots=True)
class MediaAsset:
    """Handle to a downloaded or generated local media asset."""
    path: str
    asset_type: AssetType
    duration: float = 0.0
    width: int = 0
    height: int = 0


@dataclass(frozen=True, slots=True)
class ClipSegment:
    """A timed visual or audio clip segment on the video timeline."""
    asset_path: str
    start_time: float
    duration: float
    text: str = ""
    crossfade_in: float = 0.0
    crossfade_out: float = 0.0


@dataclass(frozen=True, slots=True)
class Timeline:
    """Full composite video timeline representation."""
    duration: float
    segments: tuple[ClipSegment, ...]
    audio_path: str | None = None
    title: str = ""
